<?php
// ... (DB Connection Setup) ...
$host = 'localhost';
$dbname = 'sg2026webDB';
$username = 'root';
$password = 'root';

try {
    $pdo = new PDO("mysql:host=localhost;dbname=sg2026webDB;charset=utf8mb4", 'root', 'root');
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // 1. DELETE existing record
    $stmt = $pdo->prepare("DELETE FROM services_content WHERE slug = :slug");
    $stmt->execute(['slug' => 'vergi-yonetim-danismanligi']);
    echo "Deleted old record.\n";

    // 2. Read JSON content from file (Generated by python script)
    $jsonFile = 'extracted_vergi_content.json';
    // Wait, python script generated content_json structure inside the SQL file as string.
    // Let's redefine the content here based on the structure we want.
    // Actually, let's just parse the SQL file's intent in a safer way.

    // Better yet: Python already has the clean JSON structure in `create_vergi_sql.py`.
    // Let's modify the python script to output a CLEAN JSON file that PHP can read and insert.

} catch (PDOException $e) {
    die("DB Error: " . $e->getMessage());
}
?>